# Generated by Django 5.2 on 2025-04-28 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('regular', 'Обычный'), ('advanced', 'Продвинутый'), ('vip', 'VIP')], default='regular', max_length=10)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('avatar', models.ImageField(blank=True, default='default.png', upload_to='avatars/')),
            ],
        ),
    ]
