# Generated by Django 5.2 on 2025-04-28 16:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='bouquets/')),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('decor', models.CharField(blank=True, choices=[('ribbon', 'Ленты'), ('box', 'Коробка'), ('garland', 'Гирлянда')], max_length=50)),
                ('vase', models.CharField(blank=True, choices=[('ceramic', 'Керамика'), ('glass', 'Стекло')], max_length=50)),
                ('delivery_date', models.CharField(blank=True, choices=[('same_day', 'В тот же день'), ('next_day', 'На следующий день')], max_length=50)),
                ('flower_type', models.CharField(choices=[('rose', 'Розы'), ('lily', 'Лилии'), ('daisy', 'Ромашки'), ('tulip', 'Тюльпаны')], max_length=50)),
                ('size', models.CharField(choices=[('standard', 'Стандарт'), ('deluxe', 'Делюкс'), ('premium', 'Премиум')], max_length=50)),
                ('has_discount', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.CharField(choices=[('interflora', 'Interflora'), ('florafresh', 'Flora Fresh'), ('local', 'Местный производитель')], default='local', max_length=50)),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название цветка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('image', models.ImageField(upload_to='flowers/', verbose_name='Изображение цветка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен для заказа')),
            ],
        ),
        migrations.CreateModel(
            name='BouquetFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество цветков')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.bouquet')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.flower')),
            ],
        ),
    ]
