# Generated by Django 5.2 on 2025-04-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='generated_bouquets/')),
            ],
        ),
        migrations.CreateModel(
            name='Greenery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='greenery/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='packaging/')),
            ],
        ),
        migrations.CreateModel(
            name='Wrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='wraps/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomBouquetFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('custom_bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.custombouquet')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.flower')),
            ],
        ),
        migrations.AddField(
            model_name='custombouquet',
            name='flowers',
            field=models.ManyToManyField(through='constructor.CustomBouquetFlower', to='flowers.flower'),
        ),
        migrations.CreateModel(
            name='CustomBouquetGreenery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('custom_bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.custombouquet')),
                ('greenery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.greenery')),
            ],
        ),
        migrations.AddField(
            model_name='custombouquet',
            name='greenery',
            field=models.ManyToManyField(through='constructor.CustomBouquetGreenery', to='constructor.greenery'),
        ),
        migrations.CreateModel(
            name='CustomBouquetPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('custom_bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.custombouquet')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.packaging')),
            ],
        ),
        migrations.AddField(
            model_name='custombouquet',
            name='packaging',
            field=models.ManyToManyField(through='constructor.CustomBouquetPackaging', to='constructor.packaging'),
        ),
    ]
